# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMenu, QTableWidgetItem
from PyQt5.QtWidgets import *
import pandas as pd


class Ui_MainWindow(object):
 def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/game/icons8-gamepad-64.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(4, 42, 83);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 150, 811, 351))
        self.tableWidget.setStyleSheet("background-color: white")
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.setColumnCount(8)
        # self.tableWidget.setRowCount(0)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setBackground(QtGui.QColor(80, 137, 198))
        # self.tableWidget.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setBackground(QtGui.QColor(0, 255, 255))
       # self.tableWidget.setHorizontalHeaderItem(2, item)
       # item = QtWidgets.QTableWidgetItem()
       # self.tableWidget.setHorizontalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(4, item)
       # item = QtWidgets.QTableWidgetItem()
      #  self.tableWidget.setHorizontalHeaderItem(5, item)
       # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(6, item)
       # item = QtWidgets.QTableWidgetItem()
       # self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 530, 161, 31))
        self.pushButton.setStyleSheet("background-color : rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 40, 121, 31))
        self.pushButton_2.setStyleSheet("background-color : rgb(255, 255, 255)\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
      #  self.pushButton_2.click()
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(650, 40, 111, 31))
        self.pushButton_3.setStyleSheet(
            "background-color : rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(560, 0, 211, 21))
        self.lineEdit.setStyleSheet("background-color: white\n"
                                    "")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 50, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 30, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white")
        self.label_4.setObjectName("label_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(480, 150, 21, 20))
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setStyleSheet("background-color:white\n"
                                        "")
        self.pushButton_7.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            "../../../Downloads/icons8-filter-24 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(580, 150, 21, 20))
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet("background-color:white\n"
                                        "")
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(280, 150, 21, 20))
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet("background-color:white\n"
                                        "")
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(190, 150, 21, 20))
        self.pushButton_10.setAutoFillBackground(False)
        self.pushButton_10.setStyleSheet("background-color:white\n"
                                         "")
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(80, 150, 21, 20))
        self.pushButton_11.setAutoFillBackground(False)
        self.pushButton_11.setStyleSheet("background-color:white\n"
                                         "")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        filter_option = [
            'Ascending',
            'Desceding'
        ]

        menu = QMenu()
        menu.triggered.connect(lambda x: print(x.text()))

        self.pushButton_11.setMenu(menu)
        self.add_menu(filter_option, menu)

        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(780, 150, 21, 20))
        self.pushButton_12.setAutoFillBackground(False)
        self.pushButton_12.setStyleSheet("background-color:white\n"
                                         "")
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setFlat(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(680, 150, 21, 20))
        self.pushButton_13.setAutoFillBackground(False)
        self.pushButton_13.setStyleSheet("background-color:white\n"
                                         "")
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon1)
        self.pushButton_13.setFlat(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(390, 150, 21, 20))
        self.pushButton_14.setAutoFillBackground(False)
        self.pushButton_14.setStyleSheet("background-color:white\n"
                                         "")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon1)
        self.pushButton_14.setFlat(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 30, 71, 16))
        self.label_5.setStyleSheet("color:white")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 70, 71, 16))
        self.label_6.setStyleSheet("color:white\n"
                                   "")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionexport_to_csv_file = QtWidgets.QAction(MainWindow)
        self.actionexport_to_csv_file.setObjectName("actionexport_to_csv_file")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionexport_to_csv_file)
        self.menufile.addAction(self.actionexit)
        self.menubar.addAction(self.menufile.menuAction())
        # self.pushButton_2.clicked.connect(self.OpenFile)
        self.pushButton_2.clicked.connect(self.dataHead)
        
        # self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

 def add_menu(self, data, menu_obj):
        if isinstance(data, dict):
            for k, v in data.items():
                sub_menu = QMenu(k, menu_obj)
                menu_obj.addMenu(sub_menu)
                self.add_menu(v, sub_menu)
        elif isinstance(data, list):
            for element in data:
                self.add_menu(element, menu_obj)
        else:
            action = menu_obj.addAction(data)
            action.setIconVisibleInMenu(False)

 def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "GamePlus"))
                # item = self.tableWidget.horizontalHeaderItem(0)
                # item.setText(_translate("MainWindow", "Name"))
                # item = self.tableWidget.horizontalHeaderItem(1)
                # item.setText(_translate("MainWindow", "Released date"))
                # item = self.tableWidget.horizontalHeaderItem(2)
                # item.setText(_translate("MainWindow", "Ratings"))
                # item = self.tableWidget.horizontalHeaderItem(3)
                # item.setText(_translate("MainWindow", "Reviews Count"))
                # item = self.tableWidget.horizontalHeaderItem(4)
                # item.setText(_translate("MainWindow", "Publisher"))
                # item = self.tableWidget.horizontalHeaderItem(5)
                # item.setText(_translate("MainWindow", "Develpor"))
                # item = self.tableWidget.horizontalHeaderItem(6)
                # item.setText(_translate("MainWindow", "genres"))
                # item = self.tableWidget.horizontalHeaderItem(7)
                # item.setText(_translate("MainWindow", "Platforms"))
                self.pushButton.setText(_translate(
                    "MainWindow", "Export to csv File"))
                self.pushButton_2.setText(_translate("MainWindow", "Start"))
                self.pushButton_3.setText(_translate("MainWindow", "Stop"))
                self.label.setText(_translate("MainWindow", "Enter URL"))
                self.label_2.setText(_translate(
                    "MainWindow", "Working Time :"))
                self.label_3.setText(_translate(
                    "MainWindow", " Rows collected :"))
                self.label_4.setText(_translate("MainWindow", "Game List"))
                self.menufile.setTitle(_translate("MainWindow", "file"))
                self.actionexport_to_csv_file.setText(
                _translate("MainWindow", "export to csv file"))
                self.actionexit.setText(_translate("MainWindow", "exit"))

#  
# def OpenFile(self):
            
            
 def dataHead(self):
            try:
                self.all_data=pd.read_csv('OneMilScrapedData.csv')
            except:
                print("Error occured while opening file")
            NumRows = len(self.all_data.index)
            self.tableWidget.setColumnCount(len(self.all_data.columns))
            self.tableWidget.setRowCount(NumRows)
            self.tableWidget.setHorizontalHeaderLabels(self.all_data.columns)

            for i in range(NumRows):
                for j in range(len(self.all_data.columns)):
                     self.tableWidget.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i, j])))
            
            self.tableWidget.resizeColumnsToContents()
            self.tableWidget.resizeRowsToContents()


# import icon_rc
if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
