# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fifth.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchData(object):
    def setupUi(self, SearchData):
        SearchData.setObjectName("SearchData")
        SearchData.resize(790, 767)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pics/download.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SearchData.setWindowIcon(icon)
        SearchData.setStyleSheet("background-color:rgb(85, 255, 255)\n"
"")
        self.gobacksearch = QtWidgets.QPushButton(SearchData)
        self.gobacksearch.setGeometry(QtCore.QRect(660, 700, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gobacksearch.setFont(font)
        self.gobacksearch.setStyleSheet("background-color:rgb(233, 255, 254)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pics/images (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gobacksearch.setIcon(icon1)
        self.gobacksearch.setIconSize(QtCore.QSize(20, 20))
        self.gobacksearch.setObjectName("gobacksearch")
        self.label_2 = QtWidgets.QLabel(SearchData)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(SearchData)
        self.progressBar.setGeometry(QtCore.QRect(150, 650, 531, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tableWidget = QtWidgets.QTableWidget(SearchData)
        self.tableWidget.setGeometry(QtCore.QRect(40, 300, 711, 331))
        self.tableWidget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.label = QtWidgets.QLabel(SearchData)
        self.label.setGeometry(QtCore.QRect(40, 20, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(SearchData)
        self.plainTextEdit.setGeometry(QtCore.QRect(560, 210, 191, 31))
        self.plainTextEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.search = QtWidgets.QPushButton(SearchData)
        self.search.setGeometry(QtCore.QRect(560, 250, 75, 23))
        self.search.setStyleSheet("background-color:rgb(233, 255, 254);\n"
"\n"
"")
        self.search.setIcon(icon)
        self.search.setObjectName("search")
        self.label_4 = QtWidgets.QLabel(SearchData)
        self.label_4.setGeometry(QtCore.QRect(510, 220, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.applyadvancedfilters = QtWidgets.QPushButton(SearchData)
        self.applyadvancedfilters.setGeometry(QtCore.QRect(40, 210, 161, 41))
        self.applyadvancedfilters.setStyleSheet("background-color:rgb(233, 255, 254)")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Pics/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.applyadvancedfilters.setIcon(icon2)
        self.applyadvancedfilters.setIconSize(QtCore.QSize(30, 30))
        self.applyadvancedfilters.setObjectName("applyadvancedfilters")
        self.label_3 = QtWidgets.QLabel(SearchData)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(SearchData)
        QtCore.QMetaObject.connectSlotsByName(SearchData)

    def retranslateUi(self, SearchData):
        _translate = QtCore.QCoreApplication.translate
        SearchData.setWindowTitle(_translate("SearchData", "SearchData"))
        self.gobacksearch.setText(_translate("SearchData", "Go Back"))
        self.label_2.setText(_translate("SearchData", "(Data Scraper and Manager)"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SearchData", "Car Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SearchData", "Milage"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SearchData", "Location"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SearchData", "Price"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SearchData", "Color"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("SearchData", "Body Type"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("SearchData", "Transmission"))
        self.label.setText(_translate("SearchData", "Auto Vehicle"))
        self.search.setText(_translate("SearchData", "Search"))
        self.label_4.setText(_translate("SearchData", "Search "))
        self.applyadvancedfilters.setText(_translate("SearchData", "Apply Advanced Filters"))
        self.label_3.setText(_translate("SearchData", "Search Data"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchData = QtWidgets.QWidget()
    ui = Ui_SearchData()
    ui.setupUi(SearchData)
    SearchData.show()
    sys.exit(app.exec_())
