# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sixth.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sorting(object):
    def setupUi(self, sorting):
        sorting.setObjectName("sorting")
        sorting.resize(788, 700)
        sorting.setStyleSheet("background-color:rgb(85, 255, 255)\n"
"")
        self.label_2 = QtWidgets.QLabel(sorting)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(sorting)
        self.label.setGeometry(QtCore.QRect(30, 30, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(sorting)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(sorting)
        self.frame.setGeometry(QtCore.QRect(70, 240, 651, 351))
        self.frame.setStyleSheet("background-color:rgb(255, 249, 175);\n"
"border :3px black; ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.method1 = QtWidgets.QComboBox(self.frame)
        self.method1.setGeometry(QtCore.QRect(200, 90, 321, 31))
        self.method1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.method1.setObjectName("method1")
        self.method1.addItem("")
        self.method1.addItem("")
        self.method1.addItem("")
        self.method1.addItem("")
        self.method1.addItem("")
        self.method1.setItemText(4, "")
        self.method2 = QtWidgets.QComboBox(self.frame)
        self.method2.setGeometry(QtCore.QRect(200, 250, 321, 31))
        self.method2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.method2.setObjectName("method2")
        self.method2.addItem("")
        self.method2.addItem("")
        self.method2.addItem("")
        self.method2.setItemText(2, "")
        self.method2.addItem("")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(80, 250, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(80, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(80, 90, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(80, 200, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.colname1 = QtWidgets.QLineEdit(self.frame)
        self.colname1.setGeometry(QtCore.QRect(200, 40, 321, 31))
        self.colname1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.colname1.setObjectName("colname1")
        self.colname2 = QtWidgets.QLineEdit(self.frame)
        self.colname2.setGeometry(QtCore.QRect(200, 200, 321, 31))
        self.colname2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.colname2.setObjectName("colname2")
        self.apply1 = QtWidgets.QPushButton(self.frame)
        self.apply1.setGeometry(QtCore.QRect(300, 130, 75, 31))
        self.apply1.setStyleSheet("background-color:rgb(193, 255, 251)")
        self.apply1.setObjectName("apply1")
        self.apply2 = QtWidgets.QPushButton(self.frame)
        self.apply2.setGeometry(QtCore.QRect(300, 290, 75, 31))
        self.apply2.setStyleSheet("background-color:rgb(193, 255, 251)")
        self.apply2.setObjectName("apply2")
        self.gobacksorting = QtWidgets.QPushButton(sorting)
        self.gobacksorting.setGeometry(QtCore.QRect(650, 620, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gobacksorting.setFont(font)
        self.gobacksorting.setStyleSheet("background-color:rgb(233, 255, 254)")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pics/images (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gobacksorting.setIcon(icon)
        self.gobacksorting.setIconSize(QtCore.QSize(20, 20))
        self.gobacksorting.setObjectName("gobacksorting")

        self.retranslateUi(sorting)
        QtCore.QMetaObject.connectSlotsByName(sorting)

    def retranslateUi(self, sorting):
        _translate = QtCore.QCoreApplication.translate
        sorting.setWindowTitle(_translate("sorting", "DataSorting"))
        self.label_2.setText(_translate("sorting", "(Data Scraper and Manager)"))
        self.label.setText(_translate("sorting", "Auto Vehicle"))
        self.label_3.setText(_translate("sorting", "Data Sorting :"))
        self.method1.setItemText(0, _translate("sorting", "Merge Sort"))
        self.method1.setItemText(1, _translate("sorting", "Bubble Sort"))
        self.method1.setItemText(2, _translate("sorting", "Insertion Sort"))
        self.method1.setItemText(3, _translate("sorting", "Slection Sort"))
        self.method2.setItemText(0, _translate("sorting", "Quick Sort"))
        self.method2.setItemText(1, _translate("sorting", "Tim Sort"))
        self.method2.setItemText(3, _translate("sorting", "Heap Sort"))
        self.label_7.setText(_translate("sorting", "Method"))
        self.label_4.setText(_translate("sorting", "Column Name"))
        self.label_5.setText(_translate("sorting", "Method"))
        self.label_6.setText(_translate("sorting", "Column Nmae"))
        self.apply1.setText(_translate("sorting", "Apply"))
        self.apply2.setText(_translate("sorting", "Apply"))
        self.gobacksorting.setText(_translate("sorting", "Go Back"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sorting = QtWidgets.QWidget()
    ui = Ui_sorting()
    ui.setupUi(sorting)
    sorting.show()
    sys.exit(app.exec_())
