from PyQt5 import QtCore, QtGui, QtWidgets

#*******************************************First File*********************************************
class Ui_Firstpage(object):
    def setupUi(self, Firstpage):
        Firstpage.setObjectName("Firstpage")
        Firstpage.resize(764, 622)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pics/images.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Firstpage.setWindowIcon(icon)
        Firstpage.setAutoFillBackground(False)
        Firstpage.setStyleSheet("background-color:rgb(85, 255, 255)\n""")
        self.label = QtWidgets.QLabel(Firstpage)
        self.label.setGeometry(QtCore.QRect(140, 40, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Firstpage)
        self.label_3.setGeometry(QtCore.QRect(170, 160, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Firstpage)
        self.label_2.setGeometry(QtCore.QRect(190, 80, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.signIn = QtWidgets.QPushButton(Firstpage)
        self.signIn.setGeometry(QtCore.QRect(490, 160, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.signIn.setFont(font)
        self.signIn.setStyleSheet("background-color:rgb(193, 255, 251)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pics/icons8-login-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signIn.setIcon(icon1)
        self.signIn.setIconSize(QtCore.QSize(50, 50))
        self.signIn.setObjectName("signIn")
        self.frame = QtWidgets.QFrame(Firstpage)
        self.frame.setGeometry(QtCore.QRect(100, 220, 551, 251))
        self.frame.setStyleSheet("background-color:rgb(255, 249, 175);\n"
"border :3px black; ")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(190, 80, 271, 31))
        self.plainTextEdit.setStyleSheet("background-color:rgb(255, 255, 255);\\nborder :3px black;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(190, 140, 271, 31))
        self.plainTextEdit_2.setStyleSheet("background-color:rgb(255, 255, 255);\\nborder :3px black;")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(100, 90, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(100, 140, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.signup = QtWidgets.QPushButton(self.frame)
        self.signup.setGeometry(QtCore.QRect(250, 190, 101, 31))
        self.signup.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Pics/download (1).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signup.setIcon(icon2)
        self.signup.setIconSize(QtCore.QSize(100, 100))
        self.signup.setObjectName("signup")
        self.pushButton_2 = QtWidgets.QPushButton(Firstpage)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 520, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:rgb(193, 255, 251)")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Pics/icons8-exit-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Firstpage)
        QtCore.QMetaObject.connectSlotsByName(Firstpage)

    def retranslateUi(self, Firstpage):
        _translate = QtCore.QCoreApplication.translate
        Firstpage.setWindowTitle(_translate("Firstpage", "SDMS"))
        self.label.setText(_translate("Firstpage", "Welcome to Auto Vehicle"))
        self.label_3.setText(_translate("Firstpage", "Already have an account? Click here"))
        self.label_2.setText(_translate("Firstpage", "(Data Scraper and Manager)"))
        self.signIn.setText(_translate("Firstpage", "Sign In"))
        self.label_4.setText(_translate("Firstpage", "Sign Up"))
        self.label_5.setText(_translate("Firstpage", "Email"))
        self.label_6.setText(_translate("Firstpage", "Password"))
        self.pushButton_2.setText(_translate("Firstpage", "Exit"))

#**************************************************************************************************************************************************

#*********************************************************Second File******************************************************************************
class Ui_LogIn(object):
    def setupUi(self, LogIn):
        LogIn.setObjectName("LogIn")
        LogIn.resize(692, 524)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pics/—Pngtree—avatar icon profile icon member_5247852.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LogIn.setWindowIcon(icon)
        LogIn.setStyleSheet("background-color:rgb(85, 255, 255)")
        self.label = QtWidgets.QLabel(LogIn)
        self.label.setGeometry(QtCore.QRect(130, 30, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LogIn)
        self.label_2.setGeometry(QtCore.QRect(180, 70, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(LogIn)
        self.label_3.setGeometry(QtCore.QRect(150, 150, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(LogIn)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 101, 81))
        self.label_4.setStyleSheet("border-image: url(Pics/—Pngtree—avatar icon profile icon member_5247852.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.emailsignup = QtWidgets.QLineEdit(LogIn)
        self.emailsignup.setGeometry(QtCore.QRect(240, 240, 311, 31))
        self.emailsignup.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.emailsignup.setObjectName("emailsignup")
        self.passwordsignup = QtWidgets.QLineEdit(LogIn)
        self.passwordsignup.setGeometry(QtCore.QRect(240, 310, 311, 31))
        self.passwordsignup.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.passwordsignup.setObjectName("passwordsignup")
        self.label_5 = QtWidgets.QLabel(LogIn)
        self.label_5.setGeometry(QtCore.QRect(130, 250, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(LogIn)
        self.label_6.setGeometry(QtCore.QRect(130, 320, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.signin = QtWidgets.QPushButton(LogIn)
        self.signin.setGeometry(QtCore.QRect(330, 380, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.signin.setFont(font)
        self.signin.setStyleSheet("background-color:rgb(193, 255, 251)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pics/icons8-login-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signin.setIcon(icon1)
        self.signin.setIconSize(QtCore.QSize(30, 30))
        self.signin.setObjectName("signin")

        self.retranslateUi(LogIn)
        QtCore.QMetaObject.connectSlotsByName(LogIn)

    def retranslateUi(self, LogIn):
        _translate = QtCore.QCoreApplication.translate
        LogIn.setWindowTitle(_translate("LogIn", "SignUp"))
        self.label.setText(_translate("LogIn", "Welcome to Auto Vehicle"))
        self.label_2.setText(_translate("LogIn", "(Data Scraper and Manager)"))
        self.label_3.setText(_translate("LogIn", "Verify Yourself:"))
        self.label_5.setText(_translate("LogIn", "Email"))
        self.label_6.setText(_translate("LogIn", "Password"))
        self.signin.setText(_translate("LogIn", "SignIn"))

#**************************************************************************************************************************************************

#*********************************************************Third File******************************************************************************
class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(668, 585)
        font = QtGui.QFont()
        font.setUnderline(True)
        MainMenu.setFont(font)
        MainMenu.setStyleSheet("background-color:rgb(85, 255, 255)\n"
"")
        self.label = QtWidgets.QLabel(MainMenu)
        self.label.setGeometry(QtCore.QRect(30, 30, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainMenu)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainMenu)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.exitmain = QtWidgets.QPushButton(MainMenu)
        self.exitmain.setGeometry(QtCore.QRect(530, 490, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.exitmain.setFont(font)
        self.exitmain.setStyleSheet("background-color:rgb(193, 255, 251)")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pics/icons8-exit-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitmain.setIcon(icon)
        self.exitmain.setIconSize(QtCore.QSize(50, 50))
        self.exitmain.setObjectName("exitmain")
        self.frame = QtWidgets.QFrame(MainMenu)
        self.frame.setGeometry(QtCore.QRect(60, 190, 531, 271))
        self.frame.setStyleSheet("background-color:rgb(255, 249, 175);\n"
"border :3px black; ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.scrapdata = QtWidgets.QPushButton(self.frame)
        self.scrapdata.setGeometry(QtCore.QRect(130, 40, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(11)
        self.scrapdata.setFont(font)
        self.scrapdata.setStyleSheet("background-color:rgb(212, 255, 249)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pics/download-icon-vector-clip-art-260nw-485354581.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scrapdata.setIcon(icon1)
        self.scrapdata.setIconSize(QtCore.QSize(50, 50))
        self.scrapdata.setObjectName("scrapdata")
        self.searchdata = QtWidgets.QPushButton(self.frame)
        self.searchdata.setGeometry(QtCore.QRect(130, 180, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(11)
        self.searchdata.setFont(font)
        self.searchdata.setStyleSheet("background-color:rgb(212, 255, 249)")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Pics/download.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchdata.setIcon(icon2)
        self.searchdata.setIconSize(QtCore.QSize(50, 45))
        self.searchdata.setObjectName("searchdata")
        self.sortdata = QtWidgets.QPushButton(self.frame)
        self.sortdata.setGeometry(QtCore.QRect(130, 110, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(11)
        self.sortdata.setFont(font)
        self.sortdata.setStyleSheet("background-color:rgb(212, 255, 249)")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Pics/images.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sortdata.setIcon(icon3)
        self.sortdata.setIconSize(QtCore.QSize(50, 50))
        self.sortdata.setObjectName("sortdata")

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Main"))
        self.label.setText(_translate("MainMenu", "Auto Vehicle"))
        self.label_2.setText(_translate("MainMenu", "(Data Scraper and Manager)"))
        self.label_3.setText(_translate("MainMenu", "Chose from the followng available options"))
        self.exitmain.setText(_translate("MainMenu", "Exit"))
        self.scrapdata.setText(_translate("MainMenu", "Scrap Data and save in csv File"))
        self.searchdata.setText(_translate("MainMenu", "Data Searching                          "))
        self.sortdata.setText(_translate("MainMenu", "Data Sorting                                   "))

#**************************************************************************************************************************************************

#*********************************************************Fourth File******************************************************************************
class Ui_datadisplay(object):
    def setupUi(self, datadisplay):
        datadisplay.setObjectName("datadisplay")
        datadisplay.resize(788, 666)
        datadisplay.setStyleSheet("background-color:rgb(85, 255, 255)\n"
"")
        self.label = QtWidgets.QLabel(datadisplay)
        self.label.setGeometry(QtCore.QRect(290, 30, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(datadisplay)
        self.label_2.setGeometry(QtCore.QRect(250, 70, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(datadisplay)
        self.progressBar.setGeometry(QtCore.QRect(130, 190, 531, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(datadisplay)
        self.label_3.setGeometry(QtCore.QRect(130, 160, 81, 16))
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(datadisplay)
        self.tableWidget.setGeometry(QtCore.QRect(40, 250, 711, 331))
        self.tableWidget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.gobackdatadisplay = QtWidgets.QPushButton(datadisplay)
        self.gobackdatadisplay.setGeometry(QtCore.QRect(660, 600, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gobackdatadisplay.setFont(font)
        self.gobackdatadisplay.setStyleSheet("background-color:rgb(233, 255, 254)")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pics/images (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gobackdatadisplay.setIcon(icon)
        self.gobackdatadisplay.setIconSize(QtCore.QSize(20, 20))
        self.gobackdatadisplay.setObjectName("gobackdatadisplay")

        self.retranslateUi(datadisplay)
        QtCore.QMetaObject.connectSlotsByName(datadisplay)

    def retranslateUi(self, datadisplay):
        _translate = QtCore.QCoreApplication.translate
        datadisplay.setWindowTitle(_translate("datadisplay", "DataDisplay"))
        self.label.setText(_translate("datadisplay", "Auto Vehicle"))
        self.label_2.setText(_translate("datadisplay", "(Data Scraper and Manager)"))
        self.label_3.setText(_translate("datadisplay", "Scraping data "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("datadisplay", "Car Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("datadisplay", "Transmission"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("datadisplay", "Milage"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("datadisplay", "Car Model"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("datadisplay", "Engine"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("datadisplay", "Body Type"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("datadisplay", "Color"))
        self.gobackdatadisplay.setText(_translate("datadisplay", "Go Back"))
    
#**************************************************************************************************************************************************

#*********************************************************Fifth File******************************************************************************
class Ui_SearchData(object):
    def setupUi(self, SearchData):
        SearchData.setObjectName("SearchData")
        SearchData.resize(790, 767)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pics/download.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SearchData.setWindowIcon(icon)
        SearchData.setStyleSheet("background-color:rgb(85, 255, 255)\n"
"")
        self.gobacksearch = QtWidgets.QPushButton(SearchData)
        self.gobacksearch.setGeometry(QtCore.QRect(660, 700, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gobacksearch.setFont(font)
        self.gobacksearch.setStyleSheet("background-color:rgb(233, 255, 254)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pics/images (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gobacksearch.setIcon(icon1)
        self.gobacksearch.setIconSize(QtCore.QSize(20, 20))
        self.gobacksearch.setObjectName("gobacksearch")
        self.label_2 = QtWidgets.QLabel(SearchData)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(SearchData)
        self.progressBar.setGeometry(QtCore.QRect(150, 650, 531, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tableWidget = QtWidgets.QTableWidget(SearchData)
        self.tableWidget.setGeometry(QtCore.QRect(40, 300, 711, 331))
        self.tableWidget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.label = QtWidgets.QLabel(SearchData)
        self.label.setGeometry(QtCore.QRect(40, 20, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(SearchData)
        self.plainTextEdit.setGeometry(QtCore.QRect(560, 210, 191, 31))
        self.plainTextEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.search = QtWidgets.QPushButton(SearchData)
        self.search.setGeometry(QtCore.QRect(560, 250, 75, 23))
        self.search.setStyleSheet("background-color:rgb(233, 255, 254);\n"
"\n"
"")
        self.search.setIcon(icon)
        self.search.setObjectName("search")
        self.label_4 = QtWidgets.QLabel(SearchData)
        self.label_4.setGeometry(QtCore.QRect(510, 220, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.applyadvancedfilters = QtWidgets.QPushButton(SearchData)
        self.applyadvancedfilters.setGeometry(QtCore.QRect(40, 210, 161, 41))
        self.applyadvancedfilters.setStyleSheet("background-color:rgb(233, 255, 254)")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Pics/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.applyadvancedfilters.setIcon(icon2)
        self.applyadvancedfilters.setIconSize(QtCore.QSize(30, 30))
        self.applyadvancedfilters.setObjectName("applyadvancedfilters")
        self.label_3 = QtWidgets.QLabel(SearchData)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(SearchData)
        QtCore.QMetaObject.connectSlotsByName(SearchData)

    def retranslateUi(self, SearchData):
        _translate = QtCore.QCoreApplication.translate
        SearchData.setWindowTitle(_translate("SearchData", "SearchData"))
        self.gobacksearch.setText(_translate("SearchData", "Go Back"))
        self.label_2.setText(_translate("SearchData", "(Data Scraper and Manager)"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SearchData", "Car Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SearchData", "Milage"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SearchData", "Location"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SearchData", "Price"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SearchData", "Color"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("SearchData", "Body Type"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("SearchData", "Transmission"))
        self.label.setText(_translate("SearchData", "Auto Vehicle"))
        self.search.setText(_translate("SearchData", "Search"))
        self.label_4.setText(_translate("SearchData", "Search "))
        self.applyadvancedfilters.setText(_translate("SearchData", "Apply Advanced Filters"))
        self.label_3.setText(_translate("SearchData", "Search Data"))

#**************************************************************************************************************************************************

#*********************************************************Fifth File******************************************************************************
class Ui_sorting(object):
    def setupUi(self, sorting):
        sorting.setObjectName("sorting")
        sorting.resize(788, 700)
        sorting.setStyleSheet("background-color:rgb(85, 255, 255)\n"
"")
        self.label_2 = QtWidgets.QLabel(sorting)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(sorting)
        self.label.setGeometry(QtCore.QRect(30, 30, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(sorting)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(sorting)
        self.frame.setGeometry(QtCore.QRect(70, 240, 651, 351))
        self.frame.setStyleSheet("background-color:rgb(255, 249, 175);\n"
"border :3px black; ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.method1 = QtWidgets.QComboBox(self.frame)
        self.method1.setGeometry(QtCore.QRect(200, 90, 321, 31))
        self.method1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.method1.setObjectName("method1")
        self.method1.addItem("")
        self.method1.addItem("")
        self.method1.addItem("")
        self.method1.addItem("")
        self.method1.addItem("")
        self.method1.setItemText(4, "")
        self.method2 = QtWidgets.QComboBox(self.frame)
        self.method2.setGeometry(QtCore.QRect(200, 250, 321, 31))
        self.method2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.method2.setObjectName("method2")
        self.method2.addItem("")
        self.method2.addItem("")
        self.method2.addItem("")
        self.method2.setItemText(2, "")
        self.method2.addItem("")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(80, 250, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(80, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(80, 90, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(80, 200, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.colname1 = QtWidgets.QLineEdit(self.frame)
        self.colname1.setGeometry(QtCore.QRect(200, 40, 321, 31))
        self.colname1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.colname1.setObjectName("colname1")
        self.colname2 = QtWidgets.QLineEdit(self.frame)
        self.colname2.setGeometry(QtCore.QRect(200, 200, 321, 31))
        self.colname2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.colname2.setObjectName("colname2")
        self.apply1 = QtWidgets.QPushButton(self.frame)
        self.apply1.setGeometry(QtCore.QRect(300, 130, 75, 31))
        self.apply1.setStyleSheet("background-color:rgb(193, 255, 251)")
        self.apply1.setObjectName("apply1")
        self.apply2 = QtWidgets.QPushButton(self.frame)
        self.apply2.setGeometry(QtCore.QRect(300, 290, 75, 31))
        self.apply2.setStyleSheet("background-color:rgb(193, 255, 251)")
        self.apply2.setObjectName("apply2")
        self.gobacksorting = QtWidgets.QPushButton(sorting)
        self.gobacksorting.setGeometry(QtCore.QRect(650, 620, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gobacksorting.setFont(font)
        self.gobacksorting.setStyleSheet("background-color:rgb(233, 255, 254)")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pics/images (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gobacksorting.setIcon(icon)
        self.gobacksorting.setIconSize(QtCore.QSize(20, 20))
        self.gobacksorting.setObjectName("gobacksorting")

        self.retranslateUi(sorting)
        QtCore.QMetaObject.connectSlotsByName(sorting)

    def retranslateUi(self, sorting):
        _translate = QtCore.QCoreApplication.translate
        sorting.setWindowTitle(_translate("sorting", "DataSorting"))
        self.label_2.setText(_translate("sorting", "(Data Scraper and Manager)"))
        self.label.setText(_translate("sorting", "Auto Vehicle"))
        self.label_3.setText(_translate("sorting", "Data Sorting :"))
        self.method1.setItemText(0, _translate("sorting", "Merge Sort"))
        self.method1.setItemText(1, _translate("sorting", "Bubble Sort"))
        self.method1.setItemText(2, _translate("sorting", "Insertion Sort"))
        self.method1.setItemText(3, _translate("sorting", "Slection Sort"))
        self.method2.setItemText(0, _translate("sorting", "Quick Sort"))
        self.method2.setItemText(1, _translate("sorting", "Tim Sort"))
        self.method2.setItemText(3, _translate("sorting", "Heap Sort"))
        self.label_7.setText(_translate("sorting", "Method"))
        self.label_4.setText(_translate("sorting", "Column Name"))
        self.label_5.setText(_translate("sorting", "Method"))
        self.label_6.setText(_translate("sorting", "Column Nmae"))
        self.apply1.setText(_translate("sorting", "Apply"))
        self.apply2.setText(_translate("sorting", "Apply"))
        self.gobacksorting.setText(_translate("sorting", "Go Back"))
#**************************************************************************************************************************************************
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Firstpage = QtWidgets.QWidget()
    ui = Ui_Firstpage()
    ui.setupUi(Firstpage)
    Firstpage.show()
    sys.exit(app.exec_())